version: '3.7'

services:
  app:
    build:
      args:
        user: monster
        uid: 1000
      context: ./docker/app
      dockerfile: Dockerfile
    image: symfony-temporal-app
    container_name: symfony-temporal-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./var/report:/opt
    networks:
      - internal

  database:
    image: mysql:5.7
    container_name: symfony-temporal-db
    restart: unless-stopped
    ports:
      - 3336:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/database:/docker-entrypoint-initdb.d
    networks:
      - internal

  webserver:
    image: nginx:alpine
    container_name: symfony-temporal-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - internal

  temporal:
    image: temporalio/auto-setup:1.13.0
    ports:
      - "7233:7233"
    environment:
      - DB=postgresql
      - DB_HOST=db-temporal
      - DB_PORT=5432
      - DB_USER=temporal
      - DB_PASSWORD=temporal

  db-temporal:
    image: postgres:13
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:

networks:
  internal:
    driver: bridge
